package org.exolin.msp.service;

import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermissions;
import java.time.LocalDateTime;

/**
 *
 * @author tomgk
 */
public class Generator
{
    public static void createServiceFile(File serviceFile, String serviceTitle, String serviceUser, Path startSh) throws IOException
    {
        PrintWriter w = new PrintWriter(serviceFile);

        w.println("[Unit]");
        w.println("Description="+serviceTitle);
        w.println("After=network.target");
        w.println("StartLimitIntervalSec=0");
        w.println();
        w.println("[Service]");
        w.println("Type=simple");
        w.println("Restart=always");
        w.println("RestartSec=1");
        w.println("User="+serviceUser);
        w.println("ExecStart=/bin/bash "+startSh.toFile().toString().replace("\\", "/"));  //TODO: replace \ with / is uhh given that this is ultimatily not used on windows
        w.println();
        w.println("[Install]");
        w.println("WantedBy=multi-user.target");
        w.close();
        if(w.checkError())
            throw new IOException("Failed to write file "+serviceFile);
    }
    
    private static void setEnv(BufferedWriter w, String name, String value) throws IOException
    {
        //safety check
        if(name.contains(" ") || value.contains(" "))
            throw new IllegalArgumentException();
        
        w.append("export ").append(name).append("=").append(value);
        w.newLine();
    }
    
    static void validateMaxHeapSize(String maxHeapSize)
    {
        if(!maxHeapSize.toLowerCase().matches("[0-9]+[kmg]"))
            throw new IllegalArgumentException("Invalid maxHeapSize: "+maxHeapSize);
    }
    
    public static void createStartSh(File file,
            String serviceName,
            String serviceUser,
            String maxHeapSize,
            
            String jarName, boolean useConfigDirectory) throws IOException
    {
        if(maxHeapSize != null)
            validateMaxHeapSize(maxHeapSize);
        
        Path path = file.toPath();
        
        try(BufferedWriter w = Files.newBufferedWriter(file.toPath()))
        {
            w.write("#Generated by "+Constants.ID+" at "+LocalDateTime.now());
            w.newLine();
            
            w.write("set -e");
            w.newLine();

            w.write("NAME="+serviceName);
            w.newLine();

            w.write("DIR=/home/"+serviceUser+"/services/$NAME");
            w.newLine();

            w.write("cd $DIR/bin");
            w.newLine();
            
            w.write("echo Starting");
            w.newLine();
            
            setEnv(w, "SERVICE_BASE_DIR", "$DIR");
            setEnv(w, "SERVICE_LOG_DIR", "$DIR/log");
            
            if(useConfigDirectory)
                setEnv(w, "SERVICE_CFG_DIR", "$DIR/cfg");

            w.write("/usr/bin/java");
            
            if(maxHeapSize != null)
                w.append(" -Xmx").append(maxHeapSize);
            
            w.append(" -jar ").append("$DIR/bin/").append(jarName);
            w.newLine();
            
            w.write("echo Stopped");
            w.newLine();
        }
        
        if(path.getFileSystem().supportedFileAttributeViews().contains("posix"))
            Files.setPosixFilePermissions(path, PosixFilePermissions.fromString("rwxr--r--"));
    }
}
